filebeat.inputs:
  - type: filestream
    id: docker-containers
    enabled: true
    prospector.scanner.symlinks: true
    parsers:
      - container:
          stream: all
          format: docker
    paths:
      - /var/lib/docker/containers/*/*-json.log

output.logstash:
  hosts: ["logstash:5044"]

logging.level: info