services:
  back:
    build:
      context: .
      dockerfile: Dockerfile
      target: back
    container_name: microcrm-back
    restart: unless-stopped
    ports:
      - "8080:8080"

  front:
    build:
      context: .
      dockerfile: Dockerfile
      target: front
    container_name: microcrm-front
    restart: unless-stopped
    depends_on:
      - back
    ports:
      - "80:80"
      - "443:443"