sonar.projectName=MicroCRM
sonar.sourceEncoding=UTF-8

sonar.sources=back/src/main/java,front/src
sonar.tests=back/src/test/java,front/src
sonar.test.inclusions=back/src/test/java/**/*.java,front/src/**/*.spec.ts
sonar.exclusions=front/src/**/*.spec.ts

sonar.java.binaries=back/build/classes/java/main
sonar.java.test.binaries=back/build/classes/java/test
