input {
  beats {
    port => 5044
  }
}

filter {

  # Si le message ressemble à du JSON, on le transforme en champs exploitables
  if [message] =~ /^\s*\{/ {
    json {
      source => "message"
      target => "parsed_json"
      tag_on_failure => []
    }
  }

  # -----------------------------
  # Logs du BACKEND
  # -----------------------------
  if [parsed_json][layer] == "backend" {
    mutate {
      add_field => {
        "service_name" => "microcrm-back"
        "event_source" => "backend"
      }
    }

    # On récupère la date du log backend
    if [parsed_json][@timestamp] {
      date {
        match => ["[parsed_json][@timestamp]", "ISO8601"]
        target => "@timestamp"
      }
    }

    # On récupère le niveau du log
    if [parsed_json][level] {
      mutate {
        add_field => { "log_level" => "%{[parsed_json][level]}" }
      }
    }

    # On remplace le champ message par le vrai message du log backend
    if [parsed_json][message] {
      mutate {
        replace => { "message" => "%{[parsed_json][message]}" }
      }
    }
  }

  # -----------------------------
  # Logs du FRONTEND
  # -----------------------------
  else if [parsed_json][request][uri] or [parsed_json][logger] == "http.log.access" {
    mutate {
      add_field => {
        "service_name" => "microcrm-front"
        "event_source" => "frontend"
      }
    }

    # On récupère la date du log frontend
    if [parsed_json][ts] {
      date {
        match => ["[parsed_json][ts]", "UNIX", "UNIX_MS", "ISO8601"]
        target => "@timestamp"
      }
    }

    # On récupère l'URL appelée
    if [parsed_json][request][uri] {
      mutate {
        add_field => { "request_path" => "%{[parsed_json][request][uri]}" }
      }
    }

    # On récupère le code HTTP
    if [parsed_json][status] {
      mutate {
        add_field => { "http_status" => "%{[parsed_json][status]}" }
      }
    }
  }

  # -----------------------------
  # Tous les autres logs sont ignorés
  # -----------------------------
  else {
    drop {}
  }

  # On met le niveau du log en majuscules
  if [log_level] {
    mutate {
      uppercase => ["log_level"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}