input {
  beats {
    port => 5044
  }
}

filter {
  if [message] =~ /^\s*\{/ {
    json {
      source => "message"
      target => "parsed_json"
      tag_on_failure => []
    }
  }

  #
  # FRONT
  #
  if [parsed_json][logger] == "http.log.access" or [parsed_json][request][uri] {
    mutate {
      add_field => {
        "service_name" => "microcrm-front"
        "event_source" => "frontend"
        "event_type" => "frontend_access"
      }
    }

    if [parsed_json][ts] {
      date {
        match => ["[parsed_json][ts]", "UNIX", "UNIX_MS", "ISO8601"]
        target => "@timestamp"
      }
    }

    if [parsed_json][request][uri] {
      mutate {
        add_field => { "request_path" => "%{[parsed_json][request][uri]}" }
      }
    }

    if [parsed_json][status] {
      mutate {
        add_field => { "http_status" => "%{[parsed_json][status]}" }
      }
    }

    if [parsed_json][level] {
      mutate {
        add_field => { "log_level" => "%{[parsed_json][level]}" }
      }
    }
  }

  #
  # BACK
  #
  else if [parsed_json][layer] == "backend" or [parsed_json][logger_name] {
    mutate {
      add_field => {
        "service_name" => "microcrm-back"
        "event_source" => "backend"
        "event_type" => "application_log"
      }
    }

    if [parsed_json][@timestamp] {
      date {
        match => ["[parsed_json][@timestamp]", "ISO8601"]
        target => "@timestamp"
      }
    }

    if [parsed_json][level] {
      mutate {
        add_field => { "log_level" => "%{[parsed_json][level]}" }
      }
    }

    if [parsed_json][logger_name] {
      mutate {
        add_field => { "logger" => "%{[parsed_json][logger_name]}" }
      }
    }

    if [parsed_json][thread_name] {
      mutate {
        add_field => { "thread" => "%{[parsed_json][thread_name]}" }
      }
    }

    if [parsed_json][message] {
      mutate {
        replace => { "message" => "%{[parsed_json][message]}" }
      }
    }
  }

  #
  # Tout le reste : on jette
  #
  else {
    drop {}
  }

  if [log_level] {
    mutate {
      uppercase => ["log_level"]
    }
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-logs-%{+YYYY.MM.dd}"
  }
}